# git abbrevations

abbr -a g "git"
abbr -a ga "git add"
abbr -a gaa "git add --all"
abbr -a gb "git branch -v"
abbr -a gc "git commit"
abbr -a gca "git commit --amend"
abbr -a gcl "git clone"
abbr -a gco "git checkout"
abbr -a gcob "git checkout -b"
abbr -a gd "git diff"
abbr -a gdc "git diff --cached"
abbr -a gf "git fetch"
abbr -a gfu "git fetch upstream"
abbr -a gm "git merge --no-ff"
abbr -a gpl "git pull --prune"
abbr -a gp "git push origin HEAD"
abbr -a gpa "git push origin --all"
abbr -a gs "git status -sb"
abbr -a gt "git tag --list"
abbr -a gw "git switch"
abbr -a gwc "git switch -c"
