# ~/.config/starship.toml

add_newline = true
command_timeout = 2000

format = """$os$username$hostname$directory$character"""
right_format = """$git_branch$nix_shell$golang$java$kotlin$python$rust$time"""

palette = "catppuccin_mocha"

[os]
disabled = false
format = "[$symbol](#50fa7b) "

[os.symbols]
Alpine = " "
AlmaLinux = " "
Amazon = " "
Arch = "󰣇"
Debian = " "
FreeBSD = " "
Kali = " "
Macos = "󰀵"
NixOS = " "
OpenBSD = "󰈺 "
RockyLinux = " "
Ubuntu = "'"
Unknown = " "
Void = " "
Windows = " "

[username]
disabled = false
format = "[$user]($style)"
style_user = "#50fa7b"
style_root = "#ff5555"
show_always = true

[hostname]
disabled = false
format = "[@$hostname](#50fa7b) "
ssh_only = false
ssh_symbol = " "

[directory]
disabled = false
format = "[$path]($style)[$read_only]($read_only_style) "
style = "#50fa7b"
read_only_style = "#ff5555"
read_only = "  "

[character]
success_symbol = "[❯](#50fa7b)"

[git_branch]
disabled = true
format = "[$symbol$branch(:$remote_branch) ]($style)"

[nix_shell]
symbol = " "
disabled = false

[golang]
symbol = " "

[java]
symbol = " "

[kotlin]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[time]
disabled = true
format = "[󱑎 $time]($style)"
style = "bright-black"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
