# ~/.config/starship.toml

palette = "catppuccin_mocha"

add_newline = true
command_timeout = 2000

format = """
$os\
$username\
$hostname\
$kubernetes\
$directory\
$git_branch\
$cmd_duration\
$line_break$character"""

[character]
success_symbol = "[❯](text)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"
vimcmd_replace_one_symbol = "[❮](purple)"
vimcmd_replace_symbol = "[❮](purple)"
vimcmd_visual_symbol = "[❮](lavender)"

[cmd_duration]
disabled = false
format = "took [$duration ]($style)"
style = "pink"
min_time = 500
min_time_to_notify = 1000
show_milliseconds = true
show_notifications = false

[directory]
disabled = false
format = "at [$path]($style)[$read_only]($read_only_style) "
style = "lavender"
home_symbol = "󰋜 ~"
read_only_style = "red"
read_only = "  "
truncate_to_repo = false

[git_branch]
disabled = false
format = "via [$symbol$branch]($style) "
style = "mauve"
symbol = " "

[hostname]
disabled = false
format = "$ssh_symbol[@$hostname](lavender) "
ssh_only = false
ssh_symbol = " "

[os]
disabled = false
format = "[$symbol](lavender) "

[os.symbols]
Arch = "󰣇"
Debian = " "
FreeBSD = " "
Macos = "󰀵"
NixOS = " "
Ubuntu = "'"
Unknown = " "
Windows = " "

[username]
disabled = false
format = "[$user]($style)"
style_user = "lavender"
style_root = "bold red"
show_always = true

[golang]
disabled = false
symbol = " "

[java]
disabled = false
symbol = " "

[kotlin]
disabled = false
symbol = " "

[kubernetes]
disabled = false
format = "via [󱃾 $context($namespace)] "

[nix_shell]
disabled = false
symbol = " "

[python]
disabled = false
symbol = " "

[rust]
disabled = false
symbol = " "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
