# ~/.config/starship.toml

palette = "tokyonight"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$docker_context\
$golang\
$java\
$kotlin\
$lua\
$python\
$rust\
\n\
$character\
$status
"""

add_newline = true

[character]
success_symbol = "[❯](bold blue)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold green)"

[status]
disabled = false
format = " [$status_code](bold red)"
show_success = false

[username]
show_always = false
style_user = "fg:lavender"
style_root = "fg:red"

[hostname]
ssh_only = true
style = "fg:lavender"

[directory]
style = "fg:blue"
format = "[$path]($style)"
truncation_length = 3

[git_branch]
symbol = ""
style = "fg:lavender"
format = " on [$symbol $branch]($style)"

[git_status]
style = "fg:lavender"
format = " ([$all_status$ahead_behind]($style) )"

[fill]
symbol = " "

[docker_context]
symbol = "🐳"
style = "fg:blue"
format = " [$symbol $context]($style)"
only_with_files = true

[golang]
symbol = ""
style = "fg:yellow"
format = " [$symbol ${version}]($style)"
detect_extensions = ["go"]
detect_files = ["go.mod"]

[java]
symbol = "☕"
style = "fg:yellow"
format = " [$symbol ${version}]($style)"
detect_extensions = ["java"]
detect_files = ["pom.xml", "build.gradle", "build.gradle.kts"]

[kotlin]
symbol = "🅺"
style = "fg:lavender"
format = " [$symbol ${version}]($style)"
detect_extensions = ["kt", "kts"]
detect_files = ["build.gradle.kts", "settings.gradle.kts"]

[lua]
symbol = " "
style = "fg:green"
format = "[$symbol($version )]($style)"

[python]
symbol = ""
style = "fg:green"
format = " [$symbol (${version})($virtualenv)]($style)"
detect_extensions = ["py"]
detect_files = ["pyproject.toml", "requirements.txt", "setup.py", "Pipfile", "tox.ini"]

[rust]
symbol = "🦀"
style = "fg:red"
format = " [$symbol ${version}]($style)"
detect_extensions = ["rs"]
detect_files = ["Cargo.toml"]

[palettes.tokyonight]
base = "#1a1b26"
surface = "#2f3549"
overlay = "#3b4261"
text = "#c0caf5"
blue = "#7aa2f7"
lavender = "#bb9af7"
green = "#9ece6a"
yellow = "#e0af68"
red = "#f7768e"
