# ~/.config/starship.toml

add_newline = false
command_timeout = 2000

format = """$os$username$hostname$kubernetes$directory$character"""
right_format = """$time"""

[os]
format = '[$symbol](#50fa7b) '
disabled = false

[os.symbols]
Arch = '󰣇'
Debian = " "
FreeBSD = " "
Macos = '󰀵'
NixOS = " "
Ubuntu = ''
Windows = ' '

[username]
format = "[$user]($style)"
style_user = "#50fa7b"
style_root = "#ff5555"
show_always = true
disabled = true

[hostname]
format = "[@$hostname](#50fa7b) "
ssh_only = false
disabled = true

# Shows current directory
[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
style = "#50fa7b"
read_only_style = "#ff5555"
read_only = "  "
disabled = false

[time]
disabled = false
format = '[󱑎 $time]($style) '
style = "bright-black"
