# ~/.config/starship.toml

palette = "tokyonight_night"

add_newline = true
command_timeout = 2000

format = """
$os\
$username\
$hostname\
$kubernetes\
$directory\
$git_branch\
$cmd_duration\
$line_break$character"""

[character]
success_symbol = "[❯](text)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"
vimcmd_replace_one_symbol = "[❮](mangenta)"
vimcmd_replace_symbol = "[❮](mangenta)"
vimcmd_visual_symbol = "[❮](cyan)"

[cmd_duration]
disabled = false
format = "took [$duration ]($style)"
style = "orange"
min_time = 10000
min_time_to_notify = 10000
show_milliseconds = true
show_notifications = false

[directory]
disabled = false
format = "at [$path]($style)[$read_only]($read_only_style) "
style = "cyan"
home_symbol = "󰋜 ~"
read_only_style = "red"
read_only = "  "
truncate_to_repo = false

[git_branch]
disabled = false
format = "via [$symbol$branch]($style) "
style = "blue"
symbol = " "

[hostname]
disabled = false
format = "$ssh_symbol[@$hostname](cyan) "
ssh_only = false
ssh_symbol = " "

[os]
disabled = false
format = "[$symbol](cyan) "

[os.symbols]
Arch = "󰣇"
Debian = " "
FreeBSD = " "
Macos = "󰀵"
NixOS = " "
Ubuntu = "'"
Unknown = " "
Windows = " "

[username]
disabled = false
format = "[$user]($style)"
style_user = "cyan"
style_root = "bold red"
show_always = true

[golang]
disabled = false
symbol = " "

[java]
disabled = false
symbol = " "

[kotlin]
disabled = false
symbol = " "

[kubernetes]
disabled = false
format = "via [󱃾 $context($namespace)] "

[nix_shell]
disabled = false
symbol = " "

[python]
disabled = false
symbol = " "

[rust]
disabled = false
symbol = " "

[palettes.tokyonight_day]
fg = "#3760bf"
bg = "#c4c8da"
black = "#e1e2e7"
red = "#f52a65"
green = "#587539"
yellow = "#8c6c3e"
blue = "#2e7de9"
magenta = "#9854f1"
cyan = "#007197"
white = "#6172b0"
orange = "#b15c00"

[palettes.tokyonight_night]
fg = "#c0caf5"
bg = "#292e42"
black = "#1a1b26"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"
orange = "#ff9e64"
