add_newline = true

[username]
format = "[$user]($style)@"
style_user = "bold #50fa7b"
style_root = "bold #ff5555"
show_always = true

[hostname]
disabled = false
format = "[$hostname](bold #50fa7b) "
ssh_only = false
trim_at = "."

[character]
format="$symbol "
success_symbol="[❯](bold #50fa7b)"
error_symbol="[✗](bold #ff5555)"

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "

[directory]
disabled = false
format = "in [$path]($style)[$read_only]($read_only_style) "
style = "bold #50fa7b"

[git_branch]
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"
