# ~/.config/starship.toml

add_newline = false
command_timeout = 1000
format = """$os$username$hostname$kubernetes$directory$git_branch$git_status"""

[character]
success_symbol=""
error_symbol=""

[os]
format = '[$symbol](bold #50fa7b) '   
disabled = false

[os.symbols]
Arch = '󰣇'
Debian = " "
FreeBSD = " "
Macos = '󰀵'
NixOS = " "
Ubuntu = ''
Windows = ' '

[username]
format = "[$user]($style)"
style_user = "bold #50fa7b"
style_root = "bold #ff5555"
show_always = true
disabled = false

[hostname]
format = "[@$hostname](bold #50fa7b) "
ssh_only = false
disabled = false

# Shows current directory
[directory]
format = 'at [$path]($style)[$read_only]($read_only_style) '
style = "bold #50fa7b"
read_only_style = "bold #ff5555"
read_only = "  "
home_symbol = "󰋜 ~"
disabled = false

[git_branch]
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"
