[user]
name = "Alexander Wolff"
email = "wolffaxn@gmail.com"

[aliases]
b = ["branch"]
n = ["new"]

[git]
push-new-bookmarks = true

[lazyjj]
diff-format = "color-words"

[revsets]
immutable = "main@origin | master@origin"

[signing]
backend = "gpg"
behavior = "own"
key = "CC475A552C299D3B"

[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()"

[ui]
default-command = "log"
paginate = "never"
