name: CI

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    # every Sunday at 5am
    - cron:  '0 5 * * 0'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Run install script
        run: ./install.sh
