name: CI

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    # every Sunday at 5am
    - cron:  '0 5 * * 0'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: [3.12.1]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Run install script
        run: ./install --verbose